# Generated by Django 5.1.6 on 2025-02-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_category_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('coffee', 'กาแฟ'), ('chocolate', 'ช็อคโกแลต'), ('cocoa', 'โกโก้'), ('tea', 'ชา'), ('milk', 'นม'), ('bakery', 'ขนม')], max_length=50),
        ),
    ]
